Small changes in the readme
Rickaym/plywood-gallery-for-vscode pull request #1
Opened 2022-05-15 13:11 UTC by kolibril13

2022-05-19 14:46 UTC, Rickaym requested changes
Thanks!

2022-05-19 14:46 UTC, Rickaym commented on README.md
> +A utility extension to insert code snippets from the project [*plywood-gallery*](https://github.com/kolibril13/plywood-gallery/)  into VS Code.
Hi mate, appreciate all the edits here, I was thinking, wouldn't it be better to just say "for graphical frameworks" rather than pointing to the PyPI core library?

It seems more intuitive and understandable to people using it as the main ideal revolves around visualizing code snippets and they probably won't be as concerned with making it or delving into technical gallery details, pointing it to a Python library might be hard as a one-line descriptor for the extension if you're just trying to see what the extension is doing. 

It would be helpful to specify this in how to make a gallery or a technical deep dive -- but I think that should be reserved on the minimal example itself where we hyperlink from here.

2022-05-19 14:46 UTC, Rickaym commented on README.md
> +- [kolibril13](https://github.com/kolibril13) for building the [plywood gallery core library](https://github.com/kolibril13/plywood-gallery) and [a minimal example](https://github.com/kolibril13/plyw
```suggestion
- [kolibril13](https://github.com/kolibril13) for building the [plywood gallery core library](https://github.com/kolibril13/plywood-gallery) and [the minimal example](https://github.com/kolibril13/plywood-gallery-minimal-example).```

2022-05-22 15:59 UTC, kolibril13 commented on README.md
> +- [kolibril13](https://github.com/kolibril13) for building the [plywood gallery core library](https://github.com/kolibril13/plywood-gallery) and [the minimal example](https://github.com/kolibril13/pl
```suggestion
- [kolibril13](https://github.com/kolibril13) for building the [plywood gallery core library](https://github.com/kolibril13/plywood-gallery) and [the minimal example](https://github.com/kolibril13/plywood-gallery-minimal-example).
```

2022-05-22 16:08 UTC, kolibril13 commented on README.md
> +A utility extension to insert code snippets from the project [*plywood-gallery*](https://github.com/kolibril13/plywood-gallery/)  into VS Code.
hmm, I see your point. At the same time I think as this extension is called "Plywood-Gallery-For-VSCode", I'd like to mention the plywood gallery repo in the first sentence. Further, I think "Graphical Frameworks" sounds a bit arbitrary in this context. What about this:

```suggestion
This extension inserts code snippets into VS Code, where the snippets are represented by images.
```

2022-05-24 12:32 UTC, Rickaym commented on README.md
> +A utility extension to insert code snippets from the project [*plywood-gallery*](https://github.com/kolibril13/plywood-gallery/)  into VS Code.
Looks great, we can go with this one.

Thank you very much.

2022-05-24 12:32 UTC, merged